version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./DjangoApp/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6543:5432"
  web:
    build: 
      context: ./DjangoApp
      dockerfile: Dockerfile
    volumes:
      - ./DjangoApp:/code
    ports:
      - "80:8000"
    depends_on:
      - db
